-
  name: 'Play for all the installs'
  hosts: all
  tasks:
    - name: 'Install packages'
      yum:
        name: "{{packages}}"
      vars:
        packages:
          - firewalld
          - mariadb-server
          - httpd
          - php
          - php-mysql
          - git
          - MySQL-python

-
  name: 'Play to start the services'
  hosts: all
  tasks:
    - name: 'Start and enable services'
      systemd:
        name: "{{item}}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - mariadb
        - httpd

-
  name: 'Configure firewall for web and database'
  hosts: all
  tasks:
    - name: 'Configure firewall for web and database'
      command: firewall-cmd --permanent --zone=public --add-port="{{item}}"
      loop:
        - 3306/tcp
        - 80/tcp

    - name: 'Reload firewall'
      command: firewall-cmd --reload

-
  name: 'Create New database in mysql'
  hosts: all
  tasks:
    - name: Create a new database with name 'ecomdb'
      mysql_db:
        name: ecomdb
        state: present

-
  name: 'Create new database user in ecomdb'
  hosts: all
  tasks:
    - name: 'Create a new database user in ecomdb'
      no_log: True
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        state: present

-
  name: 'Load data to database from script'
  hosts: all
  collections:
    - community.mysql.mysql_query
  tasks:
    - name: 'Load data to database from script'
      mysql_query:
        login_db: ecomdb
        query:
          - CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1
          - INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png")

-
  name: 'Checkout the project from github'
  hosts: all
  tasks:
    - name: 'Checkout the project from github'
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        force: yes

-
  name: 'Change index.html to index.php'
  hosts: all
  tasks:
    - name: 'Change index.html to index.php'
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '/index.html'
        replace: '/index.php/'

    - name: 'Change to localhost'
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'

-
  name: 'Restart httpd service'
  hosts: all
  tasks:
    - name: Restart service httpd, in all cases
      service:
        name: httpd
        state: restarted

-
  name: 'Verify the site'
  hosts: all
  tasks:
    - name: 'Verify the site'
      uri:
        url: http://localhost
